/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AvgToMsg.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f2bbd4fe97e72bd0951f247bb023a3a8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mesa/AvgToMsg.h>
// pydoc.h is automatically generated in the build directory
#include <AvgToMsg_pydoc.h>

void bind_AvgToMsg(py::module& m)
{

    using AvgToMsg    = ::gr::mesa::AvgToMsg;


    py::class_<AvgToMsg, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<AvgToMsg>>(m, "AvgToMsg", D(AvgToMsg))

        .def(py::init(&AvgToMsg::make),
           py::arg("veclen"),
           D(AvgToMsg,make)
        )
        




        
        .def("setHold",&AvgToMsg::setHold,       
            py::arg("newValue"),
            D(AvgToMsg,setHold)
        )

        ;




}








