/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LongTermIntegrator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cc1d80f3c52ba213403f0111cc430f64)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <mesa/LongTermIntegrator.h>
// pydoc.h is automatically generated in the build directory
#include <LongTermIntegrator_pydoc.h>

void bind_LongTermIntegrator(py::module& m)
{

    using LongTermIntegrator    = ::gr::mesa::LongTermIntegrator;


    py::class_<LongTermIntegrator, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<LongTermIntegrator>>(m, "LongTermIntegrator", D(LongTermIntegrator))

        .def(py::init(&LongTermIntegrator::make),
           py::arg("fftsize"),
           py::arg("normalize"),
           D(LongTermIntegrator,make)
        )
        




        
        .def("reset",&LongTermIntegrator::reset,       
            py::arg("bReset"),
            D(LongTermIntegrator,reset)
        )

        ;




}








